{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0b1a693b-de14-41a7-aac4-5ed4f194e797",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "from data_manager import DataManager\n",
    "from market_checker import WarframeMarketChecker\n",
    "from notification_manager import NotificationManager\n",
    "\n",
    "def run_market_check(data_mgr: DataManager, market: WarframeMarketChecker, notifier: NotificationManager):\n",
    "    print(\"\\n--- Running Market Price Sweep ---\")\n",
    "    users = data_mgr.get_users()\n",
    "    all_tracked = data_mgr.get_tracked_items()\n",
    "\n",
    "    if not users:\n",
    "        print(\"No registered users found.\")\n",
    "        return\n",
    "\n",
    "    for user in users:\n",
    "        user_email = user.get(\"email\")\n",
    "        user_name = user.get(\"firstName\", \"Tenno\")\n",
    "        user_items = [i for i in all_tracked if i.get(\"userEmail\") == user_email]\n",
    "\n",
    "        if not user_items:\n",
    "            print(f\"No tracked items for {user_email}.\")\n",
    "            continue\n",
    "\n",
    "        print(f\"\\nProcessing alerts for: {user_name} ({user_email})\")\n",
    "        matched_deals = []\n",
    "        unmatched_deals = []\n",
    "\n",
    "        for entry in user_items:\n",
    "            item_name = entry.get(\"itemName\")\n",
    "            target_price = int(entry.get(\"targetPrice\", 0))\n",
    "            slug = entry.get(\"itemUrlSlug\") or market.format_item_slug(item_name)\n",
    "\n",
    "            best_order = market.get_best_order(slug)\n",
    "\n",
    "            if best_order:\n",
    "                current_price = best_order.get(\"platinum\")\n",
    "                seller_ign = best_order.get(\"user\", {}).get(\"ingame_name\")\n",
    "\n",
    "                if current_price <= target_price:\n",
    "                    whisper = market.generate_chat_command(seller_ign, item_name, current_price)\n",
    "                    matched_deals.append({\n",
    "                        \"name\": item_name,\n",
    "                        \"target_price\": target_price,\n",
    "                        \"current_price\": current_price,\n",
    "                        \"seller\": seller_ign,\n",
    "                        \"whisper\": whisper\n",
    "                    })\n",
    "                else:\n",
    "                    unmatched_deals.append({\n",
    "                        \"name\": item_name,\n",
    "                        \"target_price\": target_price,\n",
    "                        \"lowest\": current_price\n",
    "                    })\n",
    "            else:\n",
    "                unmatched_deals.append({\n",
    "                    \"name\": item_name,\n",
    "                    \"target_price\": target_price,\n",
    "                    \"lowest\": \"None Ingame\"\n",
    "                })\n",
    "\n",
    "        # Send one consolidated email per user\n",
    "        notifier.send_notification(user_email, user_name, matched_deals, unmatched_deals)\n",
    "\n",
    "def register_user(data_mgr: DataManager):\n",
    "    print(\"\\n=== User Registration ===\")\n",
    "    first_name = input(\"Enter First Name: \").strip()\n",
    "    last_name = input(\"Enter Last Name: \").strip()\n",
    "    email = input(\"Enter Email: \").strip()\n",
    "    \n",
    "    if data_mgr.add_user(first_name, last_name, email):\n",
    "        print(\"[SUCCESS] Account created successfully.\")\n",
    "    else:\n",
    "        print(\"[FAIL] Could not register user.\")\n",
    "\n",
    "def add_item_alert(data_mgr: DataManager, market: WarframeMarketChecker):\n",
    "    print(\"\\n=== Add Item Price Alert ===\")\n",
    "    email = input(\"Enter your registered Email: \").strip()\n",
    "    item_name = input(\"Item Name (e.g., Nidus Prime Chassis): \").strip()\n",
    "    target_price = int(input(\"Target Max Price (Platinum): \").strip())\n",
    "\n",
    "    slug = market.format_item_slug(item_name)\n",
    "    if data_mgr.add_tracked_item(email, item_name, target_price, slug):\n",
    "        print(f\"[SUCCESS] Tracking '{item_name}' at max {target_price} pl.\")\n",
    "    else:\n",
    "        print(\"[FAIL] Could not save tracked item.\")\n",
    "\n",
    "def main():\n",
    "    data_mgr = DataManager()\n",
    "    market = WarframeMarketChecker()\n",
    "    notifier = NotificationManager()\n",
    "\n",
    "    while True:\n",
    "        print(\"\\n==============================\")\n",
    "        print(\" WARFRAME MARKET ALERT CLUB \")\n",
    "        print(\"==============================\")\n",
    "        print(\"1. Register New User\")\n",
    "        print(\"2. Add Item Price Alert\")\n",
    "        print(\"3. Run Price Check & Dispatch Emails\")\n",
    "        print(\"4. Exit\")\n",
    "        choice = input(\"Select an option (1-4): \").strip()\n",
    "\n",
    "        if choice == \"1\":\n",
    "            register_user(data_mgr)\n",
    "        elif choice == \"2\":\n",
    "            add_item_alert(data_mgr, market)\n",
    "        elif choice == \"3\":\n",
    "            run_market_check(data_mgr, market, notifier)\n",
    "        elif choice == \"4\":\n",
    "            print(\"Exiting. Good hunting, Tenno!\")\n",
    "            sys.exit(0)\n",
    "        else:\n",
    "            print(\"Invalid selection.\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
