import datetime
import requests
from bs4 import BeautifulSoup
from ytmusicapi import YTMusic

year = input("Enter year: ")
month = input("Enter month: ")
day = input("Enter day: ")

try:
    valid_date = datetime.datetime(year=int(year), month=int(month), day=int(day))
    selected_date = valid_date.strftime("%Y-%m-%d")
    
    url = f"https://appbrewery.github.io/billboard-hot-100/{selected_date}/"
    response = requests.get(url)
    response.raise_for_status()
    text_to_work = response.text
    print(f"Successfully loaded data for {selected_date}")

    soup = BeautifulSoup(text_to_work, "html.parser")
    articles = soup.find_all(name="h3", class_="chart-entry__title")
    
    song_titles = [article.getText().strip() for article in articles]
    
    print("Connecting to YouTube Music...")
    ytmusic = YTMusic('headers_auth.json')
    
    video_ids = []
    for song in song_titles:
        search_results = ytmusic.search(query=song, filter="songs", limit=1)
        if search_results:
            video_ids.append(search_results[0]['videoId'])
            print(f"Found: {song}")
        else:
            print(f"Could not find: {song}")
            
    if video_ids:
        print("Creating playlist...")
        playlist_id = ytmusic.create_playlist(
            title=f"Hot 100 - {selected_date}", 
            description="Generated by my Python script"
        )
        ytmusic.add_playlist_items(playlist_id, video_ids)
        print(f"Success! Check your YouTube Music library for the new playlist.")
    else:
        print("No songs were found to add to a playlist.")

except ValueError:
    print("Please enter a valid date (e.g., year: 2020, month: 12, day: 31).")
except requests.exceptions.RequestException as e:
    print(f"Error fetching the webpage: {e}")
